name: transformers
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tqdm
  - librosa
  - numpy
  - pysoundfile
  - nltk
  - matplotlib
  - torchvision
  - pytorch
  - torchaudio
  - pytorch-cuda
  - tensorboard
  - tokenizers
