name: transformers
channels:
  - defaults
dependencies:
  - python=3.11
  - torchvision
  - pytorch-cuda=12.1
  - tqdm
  - librosa
  - torchaudio
  - pytorch
  - pysoundfile
  - nltk
  - conda-forge::tensorboard
  - conda-forge::tokenizers
  - conda-forge::matplotlib
